name: Remote SSH Deploy

on:
  push:
    branches:
      - main
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: ${{ secrets.SCRIPT }}
